// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace DbManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("DbManager.Models.DailyMenu", b =>
                {
                    b.Property<Guid>("DmId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DmDate");

                    b.Property<string>("DmItems");

                    b.HasKey("DmId");

                    b.ToTable("DailyMenus");
                });

            modelBuilder.Entity("DbManager.Models.FoodProduct", b =>
                {
                    b.Property<Guid>("MiId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MiCategory");

                    b.Property<byte[]>("MiImage");

                    b.Property<string>("MiName");

                    b.Property<float>("MiPrice");

                    b.HasKey("MiId");

                    b.ToTable("FoodProducts");
                });

            modelBuilder.Entity("DbManager.Models.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Level");

                    b.Property<string>("Logger");

                    b.Property<string>("Message");

                    b.HasKey("LogId");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
